name: Pan1.me Auto Check-in

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  check-in-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run check-in script
        env:
          # --- 必需的环境变量 ---
          PAN_COOKIES: ${{ secrets.PAN_COOKIES }}
          
          # --- 可选的推送渠道环境变量 ---
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
        run: python checkin.py
